// Builds dist/tokens.css (--qds-* custom properties) and dist/theme.css
// (a Tailwind v4 @theme mapping) from the DTCG JSON token sources using
// Style Dictionary v5 for reference resolution.
import { readFileSync, mkdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const distDir = path.join(root, "dist");
mkdirSync(distDir, { recursive: true });

function kebab(name) {
  return name.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
}

/** Flattens a DTCG token tree into `{ "path.joined.by.dot": token }`. */
function flatten(tree, prefix = []) {
  const out = {};
  for (const [key, value] of Object.entries(tree)) {
    if (key.startsWith("$")) continue;
    if (value && typeof value === "object" && "$value" in value) {
      out[[...prefix, key].join(".")] = value;
      // a token node can itself have nested child tokens (e.g. brand.subtle)
      const nested = flatten(value, [...prefix, key]);
      Object.assign(out, nested);
    } else if (value && typeof value === "object") {
      Object.assign(out, flatten(value, [...prefix, key]));
    }
  }
  return out;
}

function resolveValue(value, all, seen = new Set()) {
  if (typeof value !== "string") return value;
  const ref = value.match(/^\{([^}]+)\}$/);
  if (!ref) return value;
  const refPath = ref[1];
  if (seen.has(refPath)) throw new Error(`Circular token reference: ${refPath}`);
  const target = all[refPath];
  if (!target) throw new Error(`Unresolved token reference: {${refPath}}`);
  return resolveValue(target.$value, all, new Set(seen).add(refPath));
}

function cssValue(token, all) {
  const resolved = resolveValue(token.$value, all);
  if (token.$type === "fontFamily" && Array.isArray(resolved)) {
    return resolved.map((f) => (f.includes(" ") ? `"${f}"` : f)).join(", ");
  }
  return resolved;
}

function toVarName(tokenPath) {
  return `--qds-${tokenPath.split(".").map(kebab).join("-")}`;
}

function loadJson(file) {
  return JSON.parse(readFileSync(path.join(root, "src", file), "utf8"));
}

const primitives = flatten(loadJson("primitives.json"));
const light = flatten(loadJson("semantic.light.json"));
const dark = flatten(loadJson("semantic.dark.json"));

const primitivesAndLight = { ...primitives, ...light };
const primitivesAndDark = { ...primitives, ...dark };

function block(selector, tokens, all) {
  const lines = Object.entries(tokens)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([tokenPath, token]) => `  ${toVarName(tokenPath)}: ${cssValue(token, all)};`);
  return `${selector} {\n${lines.join("\n")}\n}`;
}

const tokensCss = [
  "/* Generated by @qashio/tokens — do not edit by hand. */",
  block(":root", primitives, primitivesAndLight),
  block(":root", light, primitivesAndLight),
  block(".dark, [data-theme=\"dark\"]", dark, primitivesAndDark),
].join("\n\n");

writeFileSync(path.join(distDir, "tokens.css"), tokensCss + "\n");

const semanticNames = Object.keys(light).sort();
const colorNames = semanticNames.filter((n) => primitivesAndLight[n].$type === "color");

const themeLines = [
  "@import \"./tokens.css\";",
  "",
  "@custom-variant dark (&:where(.dark, .dark *));",
  "",
  "@theme inline {",
  ...colorNames.map((n) => `  --color-${n.split(".").map(kebab).join("-")}: var(${toVarName(n)});`),
  "  --radius-sm: var(--qds-radius-sm);",
  "  --radius-md: var(--qds-radius-md);",
  "  --radius-lg: var(--qds-radius-lg);",
  "  --radius-xl: var(--qds-radius-xl);",
  "  --radius-full: var(--qds-radius-full);",
  "  --font-sans: var(--qds-font-sans);",
  "  --font-mono: var(--qds-font-mono);",
  "}",
];

writeFileSync(path.join(distDir, "theme.css"), themeLines.join("\n") + "\n");

console.log("qds tokens built: dist/tokens.css, dist/theme.css");
