// AUTO-GENERATED by apps/playground/scripts/generate-components-page.mjs — do not
// hand-edit this file. Add or change a component's demo by editing the __DOC ... DOC__
// (or __DOC_BLOCK ... DOC__ for a full-width demo) comment in its source file, then run:
//   pnpm --filter playground run docs:gen
import * as React from "react";
import * as QDS from "@qashio/ui";
import * as Finance from "@qashio/finance-ui";
import * as Icons from "lucide-react";

function Section({
  title,
  children,
  align = "row",
}: {
  title: string;
  children: React.ReactNode;
  align?: "row" | "block";
}) {
  return (
    <section className="flex flex-col gap-3">
      <h2 className="text-sm font-semibold uppercase tracking-wide text-muted-foreground">{title}</h2>
      <div
        className={
          align === "row"
            ? "flex flex-wrap items-center gap-4 rounded-lg border border-border bg-surface p-4"
            : "overflow-hidden rounded-lg border border-border bg-surface"
        }
      >
        {children}
      </div>
    </section>
  );
}

export function ComponentsPage() {
  return (
    <div className="flex flex-col gap-8">
      <QDS.PageHeader
        icon={<Icons.LayoutGrid className="size-5" />}
        title="Components"
        description="Every component and variant, grouped by atomic level."
      />

      <div>
        <h1 className="mb-3 flex items-center gap-2 text-base font-semibold">
          <Icons.Palette className="size-4" /> Atoms
        </h1>
        <div className="flex flex-col gap-6">
          <Section title="Avatar" align="row">
<QDS.Avatar name="Admin User" />
<QDS.Avatar name="Sara Al Farsi" />
          </Section>
          <Section title="Badge" align="row">
<div className="flex flex-col gap-3">
  <div className="flex flex-wrap items-center gap-2">
    {(["neutral", "brand", "brand-subtle", "success", "warning", "danger", "info", "outline"] as const).map((t) => (
      <QDS.Badge key={t} tone={t}>
        {t}
      </QDS.Badge>
    ))}
  </div>
  <div className="flex flex-wrap items-center gap-2">
    {(["sm", "md", "lg"] as const).map((s) => (
      <QDS.Badge key={s} tone="brand" size={s}>
        {s}
      </QDS.Badge>
    ))}
  </div>
</div>
          </Section>
          <Section title="Button" align="row">
{(["primary", "brand", "secondary", "outline", "brand-outline", "ghost", "destructive", "link"] as const).map((v) => (
  <QDS.Button key={v} variant={v}>
    {v}
  </QDS.Button>
))}
          </Section>
          <Section title="Checkbox" align="row">
{(function Demo() {
  const [checked, setChecked] = React.useState<boolean | "indeterminate">(true);
  return <QDS.Checkbox checked={checked} onCheckedChange={setChecked} />;
})()}
          </Section>
          <Section title="Input" align="row">
<QDS.Input placeholder="you@qashio.com" />
          </Section>
          <Section title="Label" align="row">
<div className="flex flex-col gap-1.5">
  <QDS.Label htmlFor="demo-label-input">Email</QDS.Label>
  <QDS.Input id="demo-label-input" placeholder="you@qashio.com" />
</div>
          </Section>
          <Section title="Separator" align="row">
<div className="flex h-8 items-center gap-2">
  Left <QDS.Separator orientation="vertical" /> Right
</div>
          </Section>
          <Section title="Skeleton" align="row">
<QDS.Skeleton className="h-8 w-32" />
          </Section>
          <Section title="Spinner" align="row">
<QDS.Spinner />
          </Section>
          <Section title="Switch" align="row">
{(function Demo() {
  const [on, setOn] = React.useState(true);
  return (
    <div className="flex flex-col gap-3">
      <QDS.Switch checked={on} onCheckedChange={setOn} />
      <div className="flex items-center gap-4">
        {(["sm", "md", "lg"] as const).map((s) => (
          <QDS.Switch key={s} size={s} checked={on} onCheckedChange={setOn} />
        ))}
      </div>
    </div>
  );
})()}
          </Section>
          <Section title="Tooltip" align="row">
<QDS.Tooltip content="A helpful hint">
  <QDS.Button variant="outline">Hover me</QDS.Button>
</QDS.Tooltip>
          </Section>
        </div>
      </div>

      <div>
        <h1 className="mb-3 text-base font-semibold">Molecules</h1>
        <div className="flex flex-col gap-6">
          <Section title="DropdownMenu" align="row">
<QDS.DropdownMenuRoot>
  <QDS.DropdownMenuTrigger asChild>
    <QDS.Button variant="outline">Open menu</QDS.Button>
  </QDS.DropdownMenuTrigger>
  <QDS.DropdownMenuContent>
    <QDS.DropdownMenuItem>Edit</QDS.DropdownMenuItem>
    <QDS.DropdownMenuItem destructive>Delete</QDS.DropdownMenuItem>
  </QDS.DropdownMenuContent>
</QDS.DropdownMenuRoot>
          </Section>
          <Section title="NavItem" align="row">
<div className="flex flex-col gap-0.5 p-2">
  <QDS.NavItem icon={<Icons.Home className="size-4" />} active>
    Home
  </QDS.NavItem>
  <QDS.NavItem icon={<Icons.Users className="size-4" />}>Companies</QDS.NavItem>
  <QDS.NavItem indent={1}>Active</QDS.NavItem>
</div>
          </Section>
          <Section title="Pagination" align="row">
{(function Demo() {
  const [page, setPage] = React.useState(4);
  return <QDS.Pagination page={page} pageCount={12} onPageChange={setPage} />;
})()}
          </Section>
          <Section title="SearchInput" align="row">
<QDS.SearchInput placeholder="Search…" className="w-64" />
          </Section>
          <Section title="SegmentedControl" align="row">
{(function Demo() {
  const [segment, setSegment] = React.useState("a");
  return (
    <QDS.SegmentedControl
      value={segment}
      onChange={setSegment}
      options={[
        { value: "a", label: "Recent" },
        { value: "b", label: "All" },
      ]}
    />
  );
})()}
          </Section>
        </div>
      </div>

      <div>
        <h1 className="mb-3 flex items-center gap-2 text-base font-semibold">
          <Icons.Boxes className="size-4" /> Organisms
        </h1>
        <div className="flex flex-col gap-6">
          <Section title="AppRail" align="row">
<div className="h-72 overflow-hidden rounded-lg border border-border">
  <QDS.AppRail
    logo={
      <div className="flex size-9 items-center justify-center rounded-lg border-2 border-brand text-brand">
        <Icons.Package className="size-5" />
      </div>
    }
    items={[
      { id: "ai", label: "AI Assistant", icon: <Icons.Sparkles className="size-5" />, active: true },
      { id: "analytics", label: "Analytics", icon: <Icons.LineChart className="size-5" /> },
    ]}
  />
</div>
          </Section>
          <Section title="DataTable" align="block">
{(function Demo() {
  const rows = [
    { name: "Saeed Al Zaabi", role: "Owner", status: "active" },
    { name: "Khalid Al Farsi", role: "Finance", status: "pending_kyb" },
    { name: "Yusuf Al Suwaidi", role: "Admin", status: "active" },
  ];
  const columns = [
    { accessorKey: "name", header: "Name" },
    { accessorKey: "role", header: "Role" },
    {
      accessorKey: "status",
      header: "Status",
      cell: ({ getValue }: any) => <Finance.StatusPill status={getValue()} />,
    },
  ];
  return (
    <div className="p-4">
      <QDS.DataTable columns={columns as any} data={rows} getRowId={(row) => row.name} />
    </div>
  );
})()}
          </Section>
          <Section title="PageHeader" align="block">
<QDS.PageHeader
  className="p-4"
  icon={<Icons.Users className="size-5" />}
  title="Companies"
  description="Manage onboarded and prospective companies."
  actions={<QDS.Button variant="brand">Create</QDS.Button>}
/>
          </Section>
          <Section title="Sidebar" align="row">
{(function Demo() {
  const [activeId, setActiveId] = React.useState("home");
  const items = [
    { id: "home", label: "Home", icon: <Icons.Home className="size-4" /> },
    {
      id: "companies",
      label: "Companies",
      icon: <Icons.Users className="size-4" />,
      children: [
        { id: "active", label: "Active" },
        { id: "pending", label: "Pending KYB" },
      ],
    },
    { id: "reports", label: "Reports", icon: <Icons.LineChart className="size-4" /> },
  ];
  return (
    <div className="h-72 overflow-hidden rounded-lg border border-border">
      <QDS.Sidebar
        items={items}
        activeId={activeId}
        onNavigate={(id) => setActiveId(id)}
        header={<span className="text-sm font-semibold">Qashio 360</span>}
      />
    </div>
  );
})()}
          </Section>
          <Section title="TablePagination" align="block">
{(function Demo() {
  const [page, setPage] = React.useState(1);
  const [pageSize, setPageSize] = React.useState(10);
  return (
    <div className="p-4">
      <QDS.TablePagination
        total={42}
        page={page}
        pageSize={pageSize}
        onPageChange={setPage}
        onPageSizeChange={setPageSize}
      />
    </div>
  );
})()}
          </Section>
          <Section title="Topbar" align="block">
<QDS.Topbar
  start={<QDS.SearchInput placeholder="Ask Qashio…" className="max-w-xs" />}
  end={<QDS.Avatar name="Admin User" />}
/>
          </Section>
        </div>
      </div>

      <div>
        <h1 className="mb-3 text-base font-semibold">Finance UI</h1>
        <div className="flex flex-col gap-6">
          <Section title="Amount" align="row">
<Finance.Amount value={125430.5} />
<Finance.Amount value={-4200} signed />
<Finance.Amount value={null} />
          </Section>
          <Section title="CardMask" align="row">
<Finance.CardMask last4="4242" />
          </Section>
          <Section title="CountryPill" align="row">
<Finance.CountryPill code="AE" />
<Finance.CountryPill code="SA" />
          </Section>
          <Section title="Flags" align="row">
<Finance.FlagAE className="h-6 w-9 rounded" />
<Finance.FlagSA className="h-6 w-9 rounded" />
          </Section>
          <Section title="StatusPill" align="row">
{(["active", "pending_kyb", "in_review", "rejected", "frozen"] as const).map((s) => (
  <Finance.StatusPill key={s} status={s} />
))}
          </Section>
        </div>
      </div>

      <div>
        <h1 className="mb-3 text-base font-semibold">Templates</h1>
        <Section title="AdminLayout">
          <p className="text-sm text-muted-foreground">
            [rail][sidebar][topbar + scrollable main], full viewport height — this whole app shell
            (the rail, sidebar, and topbar around this page) <em>is</em> an <code>AdminLayout</code>, so it's
            demonstrated by every page rather than nested here.
          </p>
        </Section>
      </div>
    </div>
  );
}
